site_name: IKSDP Documentation
#plugins:
#   - i18n:
#       default_language: en
#       languages:
#         en: English
#         de: Deutsch
#         it: Italiano
  # - pdf-export:
  #     media_type: print
nav:
  - English:
      - Project Documentation: en/project.md
      - User Documenation:
        - General: en/user.md
        - Jitsi Meeting Tool: en/user/how-to-jitsi.md
      - Poweruser Documenation: en/poweruser.md
      - Developer Documentation: en/developer.md
  - Deutsch:
      - Projektdokumentation: de/project.md
      - Benutzerdokumentation:
        - Allgemein: de/user.md
        - Jitsi Videokonferenz: de/user/how-to-jitsi.md
      - Poweruserdokumentation: de/poweruser.md
      - Entwicklerdokumentation: de/developer.md
  - Italiano:
      - Documentazione di progetto: it/project.md
      - Documentazione per l'utente:
        - Generale: it/user.md
        - Videoconferenza Jitsi: it/user/how-to-jitsi.md
      - Documentazione per Poweruser: it/poweruser.md
      - Documentazione per sviluppatori: it/developer.md

theme: 
  name: readthedocs

plugins:
  - open-in-new-tab:
      add_icon: true